name: Run check_lint and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f Pipfile ]; [ then pip install pipenv ] && [ pipenv shell ] && [ pipenv install ]; fi
      - name: Check lint
        run: |
          make check_lint
      - name: Test with pytest
        run: |
          python -m pytest
      - name: Check coverage
        run: |
          python -m pytest --cov=modules